spring:
  # app 이름
  application:
    name: bbs
  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##board
    password: board1234

# 웹서버 포트
server:
  port: 9080